### PR TITLE
Use `"armor"` instead of separate values

### PR DESCRIPTION
**Pull request by UmbralReaper**
There is a trend in Cataclysm-DDA (https://github.com/CleverRaven/Cataclysm-DDA/pull/49679 and similar) to use `"armor"` instead of explicitly declaring the different parts.

### CODE REVIEW

**Comment by UmbralReaper** [comment]
This isn't ready to merge - I'm unsure whether this is compatible with 0.F stable.

**Comment by TheGoatGod** [comment]
https://www.codefactor.io/repository/github/gmc-modding-team/community-mod-compilation-redux/pull/128
image

**Comment by TheGoatGod** [comment]
i like this and kind of want this, its cleaner

**Comment by TheGoatGod** [comment]
i might be mistaken, but im sure your python tool has done something wrong
this is from json_info.md
```json
"armor_data" : {      
    "covers" : [ "foot_l", "foot_r" ],
    "warmth" : 10,
    "environmental_protection" : 0,
    "encumbrance" : 0,
    "coverage" : 80,
    "material_thickness" : 1,
    "power_armor" : false
}
```

**Comment by UmbralReaper** [comment]
@TheGoatGod Yes, this is definitely incorrect. I'm trying to find the tool now, and should have a corrected PR up by tomorrow.

**Pull request closed without merging**
